#!/usr/bin/env python3
"""Writes port/linux/src/ae_font_data.c: AE's title face, port/assets/fonts/OpenCE-Regular.ttf, as C data for the
AE menus' renderer (port/linux/src/ae_font_embedded.c). Overpass comes from upstream's embedded fonts
(text_hires_embedded[], tools/embed_assets.py); OpenCE is not among them (fonts.json does not list it), so AE
carries its own copy, committed, and this tool keeps it current:

    python3 tools/ae_font_data.py           # writes the file
    python3 tools/ae_font_data.py --check   # exit 1 when the committed file differs from what it would write

The data are little-endian 32-bit words, padded with zeros, packed as tools/embed_assets.py packs its fonts (Android's
assembly rewriter garbles long byte strings)."""

import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT = Path("port/assets/fonts/OpenCE-Regular.ttf")
OUTPUT = Path("port/linux/src/ae_font_data.c")


def words(data: bytes) -> list:
    """data as lines of 32-bit words (padded with zeros), as tools/embed_assets.py words() writes them."""
    padded = data + b"\0" * (-len(data) % 4)
    values = struct.unpack(f"<{len(padded) // 4}I", padded)
    return ["\t" + ", ".join(f"0x{word:08x}" for word in values[start:start + 8]) + ","
            for start in range(0, len(values), 8)]


def text() -> str:
    """The file's text."""
    data = (ROOT / FONT).read_bytes()
    lines = [
        f"/* generated by tools/ae_font_data.py from {FONT.as_posix()}: do not edit */",
        "#ifdef HALO_GAME_BROWSER",
        "const unsigned int ae_font_opence[] = {",
        *words(data),
        "};",
        f"const unsigned int ae_font_opence_size = {len(data)};",
        "#endif",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    wanted = text()
    output = ROOT / OUTPUT
    if sys.argv[1:] == ["--check"]:
        if not output.is_file() or output.read_text() != wanted:
            print(f"{OUTPUT.as_posix()} is not current: run python3 tools/ae_font_data.py")
            return 1
        return 0
    if sys.argv[1:]:
        print("usage: ae_font_data.py [--check]")
        return 2
    output.write_text(wanted)
    return 0


if __name__ == "__main__":
    sys.exit(main())
