#!/usr/bin/env python3
"""Embeds the dedicated server's web admin page (server/webui) in the
server as C data (server/platform/control_web.h's control_web_assets):

    python tools/embed_webui.py OUTPUT.c

Each file of server/webui is served at /<its name>, and / is index.html.
The server's Content-Security-Policy allows no inline script or style, so
a page with any (a <script> with a body, a <style>, a style= or on...=
attribute, a javascript: URL) is refused here rather than broken in a
browser. tools/server_build.py runs it for every server build, and
tools/test_server_control.py for the tests.
"""

import os
import re
import sys
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent.parent
WEBUI = Path("server/webui")
TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".svg": "image/svg+xml",
}
# what a strict Content-Security-Policy would block in a page
INLINE = [
    (re.compile(r"<script(?![^>]*\bsrc=)[^>]*>", re.I), "a <script> without src"),
    (re.compile(r"<style", re.I), "a <style> element"),
    (re.compile(r"\sstyle\s*=", re.I), "a style= attribute"),
    (re.compile(r"\son[a-z]+\s*=", re.I), "an on...= handler"),
    (re.compile(r"javascript:", re.I), "a javascript: URL"),
]


def webui_inputs() -> List[Path]:
    """The page's files, as the build depends on them (sorted)."""
    folder = ROOT / WEBUI
    if not folder.is_dir():
        return []
    return sorted(WEBUI / path.name for path in folder.iterdir()
                  if path.is_file() and path.suffix in TYPES)


def check_inline(name: str, text: str) -> None:
    for pattern, what in INLINE:
        match = pattern.search(text)
        if match:
            raise SystemExit(f"{WEBUI / name}: {what} ({match.group(0).strip()}); the server's "
                             "Content-Security-Policy allows none: put it in app.js or app.css")


def generate(output: Path) -> None:
    # (the header by its path from the output's folder: the build's, or a
    # test's)
    header = os.path.relpath(ROOT / "server" / "platform" / "control_web.h", output.resolve().parent)
    lines = [
        "/* generated by tools/embed_webui.py from server/webui: do not edit */",
        "",
        f'#include "{Path(header).as_posix()}"',
        "",
    ]
    table = []
    for index, path in enumerate(webui_inputs()):
        data = (ROOT / path).read_bytes()
        if path.suffix in (".html", ".svg"):
            check_inline(path.name, data.decode("utf-8"))
        lines.append(f"static const unsigned char asset_{index}[{max(len(data), 1)}] = {{")
        for start in range(0, len(data), 24):
            lines.append("\t" + ", ".join(f"0x{byte:02x}" for byte in data[start:start + 24]) + ",")
        lines.append("};")
        table.append(f'\t{{ "/{path.name}", "{TYPES[path.suffix]}", asset_{index}, {len(data)} }},')
    lines += ["", "const struct control_web_asset control_web_assets[] =", "{"]
    lines += table or ['\t{ "", "", 0, 0 },']
    lines += ["};", "", f"const int control_web_asset_count = {len(table)};", ""]
    text = "\n".join(lines)
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.is_file() or output.read_text() != text:
        output.write_text(text)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    generate(Path(sys.argv[1]))
